### ISSUE TITLE
[Feature] To give me monitoring health of my applications

### ISSUE THREAD

**Issue by jon-shanks** [appvia/appvia-hub#117]
**What problem do you have that this product could help with and why? Please describe.**
When I have my resources provisioned and artifacts built. once i deploy my applications I currently have no easy way to visualise what is going on inside the namespace i.e. there is no monitoring dashboards or any visual view of the health of my applications, deployments etc. It would be really useful to be able to see some metrics related to what i have deployed and also allow me to append my own custom metrics too to these dashboards. 

**Describe the solution you'd like**
After i have deployed my application, i would quite like to be able to see some dashboards for the health of my applications that i have deployed i.e. be able to either see dashboards in the hub itself or link me to somewhere to view them and allow me flexibility to curate the right level of information for myself to know if i have any application problems.

**What value would this add?**
This would give me good visibility of my application and make me aware of any potential issues either during deployment or during the run phase

**Any additional comments**

**Comment by jon-shanks** [comment]
This is linked somewhat to #57

**Comment by danielwhatmuff** [comment]
As discussed with @jon-shanks and @jits...

We are going to assume initially that grafana and prometheus are both deployed to the cluster. The integration configuration will contain basic auth, an API key, URL and ca cert for speaking to a grafana API. The health check will use the data source list endpoint to check there is at least one configured. The hub will facilitate the creation of one dashboard per namespace (probably using a template like https://grafana.com/dashboards/6417) and provide a link through to the grafana URL.

**Comment by danielwhatmuff** [comment]
WIP here - https://github.com/appvia/hub-grafana-agent

**Comment by danielwhatmuff** [comment]
Have published `0.0.1-rc1` container for testing. Work under way to integrate with the hub.

**Comment by jits** [comment]
Hub integration bits in: https://github.com/appvia/appvia-hub/pull/135

**Comment by jits** [comment]
Latest hub bits now running on https://hub-demo.aws.appvia.io – fixing up agent bits now.

**Comment by danielwhatmuff** [comment]
Grafana / prometheus deployed - https://grafana-demo.aws.appvia.io/

**Comment by jits** [comment]
- [ ] Need to fix the project resources bootstrap page + backend logic to not create a separate standalone `MonitoringDashboard` resource (it will fail anyway as it won't be associated with a parent).

**Comment by jits** [comment]
Marking this as closed now… can create separate tickets for further work.
