### ISSUE TITLE
[Feature] Using GitHub as an identity provider for the hub and across provider integrations

### ISSUE THREAD

**Issue by jits** [appvia/appvia-hub#157]
**What problem do you have that this product could help with and why? Please describe.**

When setting up the hub, I would like to use GitHub as my identity provider for user access to the hub, as well as access to as many of the provider integrations as possible.

**Describe the solution you'd like**

A way to configure the hub to use GitHub as the identity provider, and then use that same identity across as many of the provider integrations as possible, and where not possible have the hub broker the access (e.g. via service tokens).

More discovery work is required to identify:
- What current integrations support GitHub?
- The user flows for various resources.
- What's in scope and out of scope?
- Supporting team structures in the hub.

**What value would this add?**

GitHub is one of the most prominent services for providing user auth. Having access to the hub be controlled via GitHub's auth would be very useful for organisations. Having this same auth propagate to all resources provisioned by the hub would create a more integrated and seamless experience for users.

**Any additional comments**

The first step is to do some research and discovery work, to identify a) what's possible, and b) the compromises, and c) the engineering effort that may be required.

**Comment by jits** [comment]
To support this case…

- https://github.com/appvia/appvia-hub/pull/158 now allows us to configure what headers will be read for the authed user.
- Then we can use https://pusher.github.io/oauth2_proxy/ in front of the hub server, to handle the auth flows with GitHub.

**Comment by jits** [comment]
- [ ] @tasharnvb / @vinn946 to test out the changes in https://github.com/appvia/appvia-hub/pull/158 once it's merged, in their demo environments set up.

**Comment by tasharnvb** [comment]
Can confirm that Github auth now works using [oauth2_proxy](https://pusher.github.io/oauth2_proxy/) with the changes from https://github.com/appvia/appvia-hub/pull/158.

**Comment by jits** [comment]
More info from previous work: https://github.com/appvia/appvia-hub/issues/41

**Comment by jits** [comment]
Writing things up in:
https://docs.google.com/document/d/14kjibyUktlU0urVCaErzCOlA68BDCNAVXOwuxn62UtI/edit?usp=sharing

**Comment by jits** [comment]
After discussion in planning today, we've decided to…

- … stick to the current flexible architecture of allowing any compatible identity provider (via an auth proxy), and only use this for managing authentication to the hub.
- … have the hub manage and be the source of truth for team structures and authorisation/RBAC.
  - This is especially important as we realise that there's not always a 1:1 mapping between the team structures and RBAC structures (e.g. for Kube RBAC we may need multiple roles for a single team, to support privileged access, etc.)
- … find ways to improve and simplify the end user process of gaining access to resources.
  - e.g. building a CLI tool that gets short lived credentials from the hub _on demand_, and sets up access to that resource locally.

**I.e. we won't be using GitHub as the source of truth.**

Main reasoning:

- Having the flexibility of identity providers could be very important in the long run.
- By managing teams directly in the hub we won't be tying ourselves to an external service, and could have more flexibility to manage the mappings.
- GitHub only really gives us easier authorisation/RBAC management of GitHub code repos and Kube clusters that can use OpenID auth. This is not deemed compelling enough.

I will finish off the doc linked above, for posterity.

**Comment by jits** [comment]
Investigation done – conclusions above – so closing this ticket.
