### ISSUE TITLE
[Feature] Provide hints to developer when resources are provisioned (WIP)

### ISSUE THREAD

**Issue by danielwhatmuff** [appvia/appvia-hub#176]
**What problem do you have that this product could help with and why? Please describe.**
After creating a space and provisioning a github repo, quay repo and kube namespace I want to clone the git repo, push an image to the docker repo and deploy my app to the namespace.

Currently I need to navigate to the code repository page to find the clone command, go to the quay documentation to find the page showing how to login/push, then go to the kube documentation to configure my kubectl config to use the credentials provided.

This takes time, requires prior knowledge of where to look for the resource specific documentation and feels repetitive. It also navigates the user away from the hub.

**Describe the solution you'd like**
I'd like to be able to create resources required for my project and then consume them quickly in order to have a deployed version of my app without too much prior knowledge of resource specific tooling and documentation sources. I'd like an end to end experience at least for the most basic/common workflow and be informed of where I can go for more detailed documentation if I feel the need for it.

**What value would this add?**

This would allow me to use only the hub UI and my command line to get an instance of my app running in a cluster with dashboards and logging. It would provide a more end to end experience.

**Any additional comments**

n/a

**Comment by jits** [comment]
Duplicate of #124?

**Comment by danielwhatmuff** [comment]
Yep, closing
