### ISSUE TITLE
ECR and platform hub

### ISSUE THREAD

**Issue by jon-shanks** [appvia/appvia-hub#20]
We need a way of creating ECR repos with RBAC based on the creation of services within the hub, or a repo potentially, depending on if a service fully maps to a repo like for like

**Comment by gambol99** [comment]
Added here https://github.com/appvia/hub-ecr-agent .. docker: quay.io/appvia/hub-ecr-agent:v0.0.1 ... 
I'll add some docs etc ..

**Comment by jits** [comment]
Marking this as closed now… can create separate tickets for further work.
