### ISSUE TITLE
[Improve Feature] Know who i am by default in crisp chat

### ISSUE THREAD

**Issue by jon-shanks** [appvia/appvia-hub#211]
**What is the current feature you would like to enhance and how does it currently work?**
Currently the crisp chat integration has no awareness of me as a user and hence when i engage in it it assumes i am a visitor, despite being logged into the hub web app and prompts me for my email address

**Describe how you would like this to be improved**
It would be good if the crisp chat had awareness of who i was within the hub and hence capture the right information so i don't have to put other details in. Also, it might encourage people to put erroneous details in as it looks separate as an integration to that of th ehub

**What value would this add?**
Saves time, feels safer and the experience is better

**Any additional comments**

**Comment by danielwhatmuff** [comment]
See https://help.crisp.chat/en/article/how-can-i-automatically-set-user-emails-udcs19/
