### ISSUE TITLE
[FEATURE] docker-compose up doesn't work

### ISSUE THREAD

**Issue by lewismarshall** [appvia/appvia-hub#212]
**Describe the feature**
If you follow the readme, you are left with no running proxy and the following error in the browser:
`dial tcp 192.168.65.2:3001: connect: connection refused`

**To Reproduce**
1. `docker-compose up`
1. open web browser @ http://localhost:3000/
1. Log in with any details

**Expected behavior**
The hub should be accessible.

**Additional context**
As there is a docker compose file - an image with the proxy should be run.

Text output below shows what's starting:
```
$ docker-compose up -d
Creating network "appvia-hub_default" with the default driver
Creating appvia-hub_grafana_agent_1     ... done
Creating appvia-hub_mock_user_service_1 ... done
Creating appvia-hub_quay_agent_1        ... done
Creating appvia-hub_postgres_1          ... done
Creating appvia-hub_ecr_agent_1         ... done
Creating appvia-hub_kube_agent_1        ... done
Creating appvia-hub_sidekiq_redis_1     ... done
Creating appvia-hub_auth_proxy_1        ... done
```

**Comment by jits** [comment]
@lewismarshall - are you running this on Linux? If so, see https://github.com/appvia/appvia-hub/issues/29
