### ISSUE TITLE
[Feature] Code best practices

### ISSUE THREAD

**Issue by jon-shanks** [appvia/appvia-hub#79]
**What feature would you like to see in the hub and why? Please describe.**
Currently when people have privileges to create repositories in the organisation, there is a manual process of configuring the repository with specific settings each time i.e. protected master branch etc. 

**Describe the solution you'd like**
It would be good to be able to define a general best practice approach for my code repositories that the hub would create. So that every repository that gets created complies with the best practice i.e. 
For master branch
- Require pull request reviews before merging 
- Require status checks to pass before merging
- Require branches to be up to date before merging

**What value would this add?**
It would allow all repositories to have a consistent setup that conform to my best practices. It would be good if the above is configurable options. 

**Any additional comments**

**Comment by gambol99** [comment]
So there appears to a an issue getting this in. Namely the github api doesn't presently allow for wildcard rules on protective branches via the API, but does through the UI. This means the branch must exist in order to set the protection on. I've raised a pr #115 which kinda of addresses this .. Effectively when creating the repo we need to drop in a feature (gitignore, readme or licence) to create `master` for us anf then set the protection. Of course this limits only to master branch.

Links:
- https://github.community/t5/GitHub-API-Development-and/REST-API-v3-wildcard-branch-protection/td-p/14547

**Comment by gambol99** [comment]
Oh, not sure if we are planning .. but the signed commits restriction is presently not available with the ruby client being used .. So will need a upstream PR ..

**Comment by jon-shanks** [comment]
Is it possible we could potentially add a webhook to notify us of when they have pushed to then implement this feature?

**Comment by gambol99** [comment]
So from glancing around, bots are the way most ppl seem to implement this .. I hang off events and trigger the actions .. Create branch, is master? boom .. add protection .. Add CI integration? boom add status restriction to master branch .. etc

**Comment by jits** [comment]
@jon-shanks – 

> Is it possible we could potentially add a webhook to notify us of when they have pushed to then implement this feature?

Yep, so since we use the new GitHub Apps, we can register an endpoint that receives webhook events (ref: https://developer.github.com/apps/differences-between-apps/#webhooks). So you what you suggest is doable, with some work.

**Comment by jon-shanks** [comment]
So an additional implementation to this, is to be able to override the global configuration of an integration with your own configuration i.e.
As a user who has created a space
And who has created a github resource
I want to be able to turn off specific global configuration because it isn't applicable to me

**Comment by jits** [comment]
For this ticket, we'll just be adding this option at a global level – i.e. as part of the integration config, and also wrapping all best practices into one single config option.

I've created https://github.com/appvia/appvia-hub/issues/122 to capture the potential need for space level overriding of this option.
